### ISSUE TITLE
ChromerDriverManager not returning correct path for the chrome driver

### ISSUE THREAD

**Issue by Hasnain-20** [SergeyPirogov/webdriver_manager#665]
**Description**
The chrome got updated on 23-07-2024 to the version 127.0.6533.72 and so does the chrome_driver. I prepared the new script and downloaded the Chrome Driver via service ChromeDriverManger from webdriver_manager .chrome. and it isn't returning the correct path of the binary. The path returned is mentioned in Error Log section.

The following files were found the downloaded chrome driver binary folder.
![image](https://github.com/user-attachments/assets/93bcee4e-0967-442c-a43e-265d3ce1c2e4)

**Browser and version**: Chrome, version 127.0.6533.72

**Operating system and architecture**: Linux x64

**Selenium version**: 4.22.0

**WebDriverManager version**: 4.0.1

**WebDriverManager call**: 
```
driver_path = ChromeDriverManager().install()
driver = webdriver.Chrome(service=Service(driver_path))
```

**Error log**: 
![image](https://github.com/user-attachments/assets/5d680b56-0bf2-4514-b565-4431207d1ff0)

**Solution**: 
I solved the issue by using following piece of code
```
driver_path = ChromeDriverManager().install()
if driver_path:
    driver_name = driver_path.split('/')[-1]
    if driver_name!="chromedriver":
        driver_path = "/".join(driver_path.split('/')[:-1]+["chromedriver"])
        os.chmod(driver_path, 0o755)
driver = webdriver.Chrome(service=Service(driver_path))

```

**Comment by mhdzumair** [comment]
+1

**Comment by DimaYurchenko** [comment]
Seems like new distribution of chromedriver includes THIRD_PARTY_NOTICES.chromedriver next to chromedriver binary.

webdriver_manager.core.driver_cache.DriverCacheManager.__get_binary
is failing to resolve the binary correctly

```    def __get_binary(self, files, driver_name):
        if not files:
            raise Exception(f"Can't find binary for {driver_name} among {files}")

        if len(files) == 1:
            return files[0]

        for f in files:
            if 'LICENSE' in f:
                continue
            if driver_name in f:
                return f

        raise Exception(f"Can't find binary for {driver_name} among {files}")```
        
      It looks for a file that contains 'chromedriver' in its name. Notice how it already has a check to skip LICENSE.chromedriver, which also lives next to binary. 
      So fix would be either adding another check to avoid resolving THIRD_PARTY_NOTICES.chromedriver or an improved way to resolve the binary to make sure this issue does not resurface if another file will be added here in future.
      
      I will be happy to open a PR to fix this, just tell me.😉

**Comment by mayconfrr** [comment]
+1

**Comment by ewagner70** [comment]
> Seems like new distribution of chromedriver includes THIRD_PARTY_NOTICES.chromedriver next to chromedriver binary.
> 
> webdriver_manager.core.driver_cache.DriverCacheManager.__get_binary is failing to resolve the binary correctly
> 
> ```
> def __get_binary(self, files, driver_name):
>         if not files:
>             raise Exception(f"Can't find binary for {driver_name} among {files}")
> 
>         if len(files) == 1:
>             return files[0]
> 
>         for f in files:
>             if 'LICENSE' in f:
>                 continue
>             if driver_name in f:
>                 return f
> 
>         raise Exception(f"Can't find binary for {driver_name} among {files}")
> ```
> 
> It looks for a file that contains 'chromedriver' in its name. Notice how it already has a check to skip LICENSE.chromedriver, which also lives next to binary.
> 
> So fix would be either adding another check to avoid resolving THIRD_PARTY_NOTICES.chromedriver or an improved way to resolve the binary to make sure this issue does not resurface if another file will be added here in future.

to be on the safe side, wouldn't the following condition be more appropriate:
`for f in files:
if driver_name==f:
return f`

or when files contains the full path:
`for f in files:
if '/'+driver_name in f:
return f`

**Comment by KfirKho** [comment]
Just to update @Hasnain-20's answer, I updated his code a bit in case you ran into the "File not found" problem:
`    if driver_path:
        driver_name = driver_path.split('/')[-1]
        if driver_name != "chromedriver":
            driver_path = "/".join(driver_path.split('/')[:-1] + ["chromedriver.exe"])
            if '/' in driver_path:
                driver_path = driver_path.replace('/', '\\')
            os.chmod(driver_path, 0o755)
    driver = webdriver.Chrome(service=ChromeService(driver_path))`

**Comment by dmit-tenable** [comment]
The complete fix should be by adding another skip condition to the for loop:

```
         for f in files:
            if 'LICENSE' in f:
                continue
            if 'THIRD_PARTY_NOTICES' in f:
                continue
            if driver_name in f:
                return f
```
                
 If you dont want to edit webdriver_manager lib (webdriver_manager/core/driver_cache.py/__get_binary())
 you can edit service path before starting the chrome webdriver service:
 
```
    service = Service(ChromeDriverManager().install())
    path = service.path
    service.path = path.replace('THIRD_PARTY_NOTICES.', "")
    os.chmod(service.path, 0o755)
    driver = webdriver.Chrome(service=service, options=options)
```

**Comment by shner-elmo** [comment]
So apparently the owner has paused this project for the war in Ukraine, what's the plan? is there somebody else who has permission to merge a PR and publish to PyPi?

**Comment by sunnyplaza** [comment]
For people like me that need a guide, we need to update a .py file to add an additional check as there is a new file being added to the chromedriver folder 

Windows, navigate to the following folder 
C:\Users\YOUR_NAME\YOU_VENV_NAME\venv\Lib\site-packages\webdriver_manager\core

or search for 'driver_cache.py' in the C drive

right click the driver_cache.py and open with notepad 


change the following text, BE CAREFUL to ensure the indentation stays the same.

```
for f in files:
            if 'LICENSE' in f:
                continue
            if driver_name in f:
                return f
```

to

```
for f in files:
            if 'LICENSE' in f:
                continue
            if 'THIRD_PARTY' in f:
                continue
            if driver_name in f:
                return f
```

and save the file. the chromedriver should run in your scripts as normal as it did before

**Comment by ggkiokas** [comment]
Can you please let us know how we can have this fix in a specific version of webdriver ?

**Comment by Jheesbrough** [comment]
@ggkiokas could you elaborate? This issue was fixed in #666. Update your version of the webdriver_manager package if you need to use the newer versions of the chrome driver.

**Comment by moriyaki** [comment]
If you just use the latest version of chromedriver.exe, there seems to be no need to use webdriver-manager.

```Python
from selenium.webdriver.chrome.webdriver import WebDriver
from selenium.webdriver.chrome.service import Service as ChromeService

driver = WebDriver(service=ChromeService())
````

**Comment by rabbit0057** [comment]
Windows Users delete all driver files from .wdm folder and re-run your script

**Comment by pweev** [comment]
> **Description** The chrome got updated on 23-07-2024 to the version 127.0.6533.72 and so does the chrome_driver. I prepared the new script and downloaded the Chrome Driver via service ChromeDriverManger from webdriver_manager .chrome. and it isn't returning the correct path of the binary. The path returned is mentioned in Error Log section.
> 
> The following files were found the downloaded chrome driver binary folder. ![image](https://private-user-images.githubusercontent.com/123731247/351623742-93bcee4e-0967-442c-a43e-265d3ce1c2e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDkyNTAsIm5iZiI6MTcyMjQ0ODk1MCwicGF0aCI6Ii8xMjM3MzEyNDcvMzUxNjIzNzQyLTkzYmNlZTRlLTA5NjctNDQyYy1hNDNlLTI2NWQzY2UxYzJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxODAyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTY2MjYyYTRlNDM4NDAzODg2ZTk0ZjdhZTRhMTAwMDFiYjgxY2IxYWUxNTFmMTM5MDAzZjM1N2YwZjFkYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QDoMLlIXE4H655L1u6sRNuxmH7tbX8r-YljN1V9KcWo)
> 
> **Browser and version**: Chrome, version 127.0.6533.72
> 
> **Operating system and architecture**: Linux x64
> 
> **Selenium version**: 4.22.0
> 
> **WebDriverManager version**: 4.0.1
> 
> **WebDriverManager call**:
> 
> ```
> driver_path = ChromeDriverManager().install()
> driver = webdriver.Chrome(service=Service(driver_path))
> ```
> 
> **Error log**: ![image](https://private-user-images.githubusercontent.com/123731247/351623090-5d680b56-0bf2-4514-b565-4431207d1ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDkyNTAsIm5iZiI6MTcyMjQ0ODk1MCwicGF0aCI6Ii8xMjM3MzEyNDcvMzUxNjIzMDkwLTVkNjgwYjU2LTBiZjItNDUxNC1iNTY1LTQ0MzEyMDdkMWZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxODAyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzVmZmI0YzkwMjg0OWU3MjYyNjc4YmQ3ZTA4NmJiZWE5NzcyNjIyNGQ2ODk2MGI2NGIzNzViMjAzZGIxOWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3WAk4ObaPXqJeRYAkDpE-x1mVokqDmRVvRTYEgaClng)
> 
> **Solution**: I solved the issue by using following piece of code
> 
> ```
> driver_path = ChromeDriverManager().install()
> if driver_path:
>     driver_name = driver_path.split('/')[-1]
>     if driver_name!="chromedriver":
>         driver_path = "/".join(driver_path.split('/')[:-1]+["chromedriver"])
>         os.chmod(driver_path, 0o755)
> driver = webdriver.Chrome(service=Service(driver_path))
> ```

I just wanted to say thank you for sharing! I discovered this last night and have been working on a fix the entire morning. I for sure thought I broke it being new to messing with grid and making changes to my requirements file.

**Comment by Pelmen323** [comment]
> driver_path = ChromeDriverManager().install()
> if driver_path:
>     driver_name = driver_path.split('/')[-1]
>     if driver_name!="chromedriver":
>         driver_path = "/".join(driver_path.split('/')[:-1]+["chromedriver"])
>         os.chmod(driver_path, 0o755)
> driver = webdriver.Chrome(service=Service(driver_path))

@pweev Thank you very much for the solution. I needed just a small tweak to make it work on Win since in my case I was still getting the error
```
    os.chmod(driver_path, 0o755)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\xxx\\.wdm\\drivers\\chromedriver\\win64\\127.0.6533.88\\chromedriver-win32/chromedriver'
```
```
driver_path = "/".join(driver_path.split('/')[:-1]+["chromedriver.exe"]).replace('/', '\\')
```

**Comment by Jheesbrough** [comment]
This issue should be closed@Pelmen323, update your package and clear the driver folder and it will work as intended.

**Comment by gonultasbu** [comment]
Removing the arg service from driver = webdriver.Chrome() worked for me too:
```
from selenium import webdriver

navegador = webdriver.Chrome()
```
reference: [https://stackoverflow.com/a/78802536/10405090](https://stackoverflow.com/a/78802536/10405090)

**Comment by CalebePrates** [comment]
chrome_path = ChromeDriverManager().install()
    if "THIRD_PARTY_NOTICES.chromedriver" in chrome_path:
        chrome_path = chrome_path.replace("THIRD_PARTY_NOTICES.chromedriver", "chromedriver")

**Comment by Jheesbrough** [comment]
This issue should be closed, update your package and clear the driver folder and it will work as intended.

**Comment by frederick0291** [comment]
Confirming that updating the `webdriver_manager` package fixed this issue on my end.

**Comment by Yangeok** [comment]
> ```
> chrome_path = ChromeDriverManager().install()
> if "THIRD_PARTY_NOTICES.chromedriver" in chrome_path:
>     chrome_path = chrome_path.replace("THIRD_PARTY_NOTICES.chromedriver", "chromedriver")
> ```

Not working, the error occurred like below:

```
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.
```

**Comment by aleksandr-kotlyar** [comment]
Fixed in
Commit: 3280b00 (Update driver_cache.py (#666))
Date: 2024-07-25 09:10:30 +0100
